// Auto-generated from Rust build script - DO NOT EDIT
// This file is generated from Rust constant values to ensure single source of truth

export const ACP_COMMANDS = {
	initialize: "acp_initialize",
	new_session: "acp_new_session",
	resume_session: "acp_resume_session",
	fork_session: "acp_fork_session",
	set_model: "acp_set_model",
	set_mode: "acp_set_mode",
	send_prompt: "acp_send_prompt",
	cancel: "acp_cancel",
	list_agents: "acp_list_agents",
	get_capabilities: "acp_get_capabilities",
} as const;

export const SESSION_HISTORY_COMMANDS = {
	get_converted_session: "get_converted_session",
	sync_project_threads: "sync_project_threads",
	sync_all_threads: "sync_all_threads",
	sync_thread: "sync_thread",
	sync_threads_background: "sync_threads_background",
	get_threads_cached: "get_threads_cached",
	trigger_initial_sync: "trigger_initial_sync",
	get_startup_threads: "get_startup_threads",
	cleanup_empty_conversations: "cleanup_empty_conversations",
	get_session_plan: "get_session_plan",
	get_plan_by_slug: "get_plan_by_slug",
	list_plans: "list_plans",
	get_cache_stats: "get_cache_stats",
	invalidate_history_cache: "invalidate_history_cache",
	reset_cache_stats: "reset_cache_stats",
} as const;

export const STORAGE_COMMANDS = {
	save_conversation_metadata: "save_conversation_metadata",
	get_conversation_metadata: "get_conversation_metadata",
	get_all_conversation_metadata: "get_all_conversation_metadata",
	delete_conversation_metadata: "delete_conversation_metadata",
	update_conversation_metadata: "update_conversation_metadata",
	delete_conversation: "delete_conversation",
	open_in_finder: "open_in_finder",
	get_projects: "get_projects",
	get_recent_projects: "get_recent_projects",
	get_project_count: "get_project_count",
	get_selected_project: "get_selected_project",
	select_project: "select_project",
	add_project: "add_project",
	remove_project: "remove_project",
	browse_project: "browse_project",
	get_all_conversations: "get_all_conversations",
	upsert_conversation: "upsert_conversation",
	get_user_setting: "get_user_setting",
	save_user_setting: "save_user_setting",
	get_thread_list_settings: "get_thread_list_settings",
	save_thread_list_settings: "save_thread_list_settings",
	save_api_key: "save_api_key",
	delete_api_key: "delete_api_key",
	get_user_keybindings: "get_user_keybindings",
	save_user_keybinding: "save_user_keybinding",
	delete_user_keybinding: "delete_user_keybinding",
	reset_keybindings_to_defaults: "reset_keybindings_to_defaults",
	request_destructive_confirmation_token: "request_destructive_confirmation_token",
} as const;

export const CURSOR_HISTORY_COMMANDS = {
	get_cursor_history: "get_cursor_history",
	get_cursor_session: "get_cursor_session",
} as const;

export const COMMANDS = {
	acp: {
		initialize: "acp_initialize",
		new_session: "acp_new_session",
		resume_session: "acp_resume_session",
		fork_session: "acp_fork_session",
		set_model: "acp_set_model",
		set_mode: "acp_set_mode",
		send_prompt: "acp_send_prompt",
		cancel: "acp_cancel",
		list_agents: "acp_list_agents",
		get_capabilities: "acp_get_capabilities",
	},
	session_history: {
		get_converted_session: "get_converted_session",
		sync_project_threads: "sync_project_threads",
		sync_all_threads: "sync_all_threads",
		sync_thread: "sync_thread",
		sync_threads_background: "sync_threads_background",
		get_threads_cached: "get_threads_cached",
		trigger_initial_sync: "trigger_initial_sync",
		get_startup_threads: "get_startup_threads",
		cleanup_empty_conversations: "cleanup_empty_conversations",
		get_session_plan: "get_session_plan",
		get_plan_by_slug: "get_plan_by_slug",
		list_plans: "list_plans",
		get_cache_stats: "get_cache_stats",
		invalidate_history_cache: "invalidate_history_cache",
		reset_cache_stats: "reset_cache_stats",
	},
	storage: {
		save_conversation_metadata: "save_conversation_metadata",
		get_conversation_metadata: "get_conversation_metadata",
		get_all_conversation_metadata: "get_all_conversation_metadata",
		delete_conversation_metadata: "delete_conversation_metadata",
		update_conversation_metadata: "update_conversation_metadata",
		delete_conversation: "delete_conversation",
		open_in_finder: "open_in_finder",
		get_projects: "get_projects",
		get_recent_projects: "get_recent_projects",
		get_project_count: "get_project_count",
		get_selected_project: "get_selected_project",
		select_project: "select_project",
		add_project: "add_project",
		remove_project: "remove_project",
		browse_project: "browse_project",
		get_all_conversations: "get_all_conversations",
		upsert_conversation: "upsert_conversation",
		get_user_setting: "get_user_setting",
		save_user_setting: "save_user_setting",
		get_thread_list_settings: "get_thread_list_settings",
		save_thread_list_settings: "save_thread_list_settings",
		save_api_key: "save_api_key",
		delete_api_key: "delete_api_key",
		get_user_keybindings: "get_user_keybindings",
		save_user_keybinding: "save_user_keybinding",
		delete_user_keybinding: "delete_user_keybinding",
		reset_keybindings_to_defaults: "reset_keybindings_to_defaults",
		request_destructive_confirmation_token: "request_destructive_confirmation_token",
	},
	cursor_history: {
		get_cursor_history: "get_cursor_history",
		get_cursor_session: "get_cursor_session",
	},
} as const;
