// This file was generated by specta. Do not edit this file manually.

// JsonValue represents any valid JSON value
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type AvailableModel = { modelId: string; name: string; description?: string | null }

export type AvailableMode = { id: string; name: string; description?: string | null }

/**
 * Command input hint.
 */
export type CommandInput = { 
/**
 * The hint can be a string or array in the protocol; we normalize to string.
 */
hint: string }

/**
 * Available command with metadata.
 */
export type AvailableCommand = { name: string; description: string; input?: CommandInput | null }

/**
 * Pre-computed model info for display. Frontend uses this directly.
 */
export type DisplayableModel = { modelId: string; displayName: string; description?: string | null }

/**
 * Generic group of models. Label can be provider, base model name, or empty.
 */
export type DisplayModelGroup = { label: string; models: DisplayableModel[] }

export type ModelDisplayFamily = "claudeLike" | "codexReasoningEffort" | "providerGrouped"

export type UsageMetricsPresentation = "contextWindowOnly" | "spendAndContext"

export type ModelPresentationMetadata = { displayFamily: ModelDisplayFamily; usageMetrics: UsageMetricsPresentation; provider?: ProviderMetadataProjection }

/**
 * Display-ready model structure. Single representation—flat = one group.
 */
export type ModelsForDisplay = { groups: DisplayModelGroup[]; presentation?: ModelPresentationMetadata }

export type SessionModelState = { availableModels?: AvailableModel[]; currentModelId?: string; modelsDisplay?: ModelsForDisplay; providerMetadata?: ProviderMetadataProjection }

export type SessionModes = { currentModeId?: string; availableModes?: AvailableMode[] }

/**
 * Configuration option value.
 */
export type ConfigOptionValue = { name: string; value: JsonValue; description?: string | null }

/**
 * Configuration option data.
 */
export type ConfigOptionData = { id: string; name: string; category: string; type: string; description?: string | null; currentValue?: JsonValue | null; options?: ConfigOptionValue[] }

export type NewSessionResponse = { sessionId: string; sequenceId?: number | null; sessionOpen?: SessionOpenResult | null; models?: SessionModelState; modes?: SessionModes; availableCommands?: AvailableCommand[]; configOptions?: ConfigOptionData[] }

export type ResumeSessionResponse = { models?: SessionModelState; modes?: SessionModes; availableCommands?: AvailableCommand[]; configOptions?: ConfigOptionData[] }

/**
 * Canonical agent identifier enum.
 * 
 * This enum represents all valid agent types in the system.
 * Parsers set the enum directly based on their context (no normalization needed).
 */
export type CanonicalAgentId = "claude-code" | "copilot" | "cursor" | "opencode" | "codex" | "forge" | 
/**
 * Custom agent registered by user
 */
{ custom: string }

/**
 * Tool kind for routing to appropriate UI components.
 */
export type ToolKind = "read" | "edit" | "execute" | "search" | "glob" | "fetch" | "web_search" | "think" | "todo" | "question" | "task" | "task_output" | "skill" | "move" | "delete" | "enter_plan_mode" | "exit_plan_mode" | "create_plan" | "tool_search" | "browser" | "sql" | "unclassified" | "other"

/**
 * Tool call status.
 */
export type ToolCallStatus = "pending" | "in_progress" | "completed" | "failed"

export type ChunkAggregationHint = "boundaryCarryover"

/**
 * A single file edit entry within an Edit tool call.
 * 
 * A single `Edit` tool call may touch multiple files (e.g., OpenCode's `patch` tool
 * or Codex's multi-entry `changes` map). Each entry represents one file's change.
 */
export type EditEntry = { 
/**
 * Path of the file being edited.
 */
filePath?: string | null; 
/**
 * Original path when the edit entry represents a rename/move inside a multi-file edit patch.
 */
moveFrom?: string | null; 
/**
 * Text being replaced (None = new file or full-file write).
 */
oldString?: string | null; 
/**
 * Replacement text (standard edit).
 */
newString?: string | null; 
/**
 * Full file content (create/overwrite variant).
 */
content?: string | null }

/**
 * Optional line range within a source file (read/search excerpts).
 */
export type ToolSourceRange = { startLine?: number | null; endLine?: number | null }

/**
 * Structured provider-supplied read context (path excerpts, ranges, metadata).
 * 
 * Kept separate from [`ToolCallLocation`] (session routing) so read tools can carry
 * rich source metadata without overloading generic location lists (R13).
 */
export type ToolSourceContext = { path?: string | null; viewRange?: ToolSourceRange | null; 
/**
 * Line-numbered or plain excerpt text from the provider (not synthesized UI copy).
 */
excerpt?: string | null }

/**
 * Tool arguments discriminated by tool kind.
 * Each variant contains exactly the fields needed for that tool type.
 */
export type ToolArguments = { kind: "read"; file_path?: string | null; source_context?: ToolSourceContext | null } | 
/**
 * Edit tool arguments.
 * 
 * `edits` is always a non-empty Vec. Single-file edits have exactly one entry;
 * multi-file edits (OpenCode `patch`, Codex multi-entry `changes` map) have N entries.
 */
{ kind: "edit"; edits: EditEntry[] } | { kind: "execute"; command?: string | null } | { kind: "search"; query?: string | null; file_path?: string | null } | { kind: "glob"; pattern?: string | null; path?: string | null } | { kind: "fetch"; url?: string | null } | { kind: "webSearch"; query?: string | null } | { kind: "think"; description?: string | null; prompt?: string | null; subagent_type?: string | null; skill?: string | null; skill_args?: string | null; raw?: JsonValue | null } | { kind: "taskOutput"; task_id?: string | null; timeout?: number | null } | { kind: "move"; from?: string | null; to?: string | null } | { kind: "delete"; file_path?: string | null; file_paths?: string[] | null } | { kind: "planMode"; mode?: string | null } | { kind: "toolSearch"; query?: string | null; max_results?: number | null } | { kind: "browser"; raw: JsonValue } | { kind: "sql"; query?: string | null; description?: string | null } | { kind: "unclassified"; raw_name: string; raw_kind_hint?: string | null; title?: string | null; arguments_preview?: string | null; signals_tried: string[] } | { kind: "other"; raw: JsonValue }

/**
 * Tool reference for permission/question requests.
 */
export type ToolReference = { messageId: string; callId: string }

/**
 * Question option.
 */
export type QuestionOption = { label: string; description: string }

/**
 * Question item.
 */
export type QuestionItem = { question: string; header: string; options: QuestionOption[]; multiSelect: boolean }

/**
 * Explicit reply routing metadata for a canonical interaction.
 */
export type InteractionReplyHandlerKind = "json_rpc" | "http"

/**
 * Backend-owned reply handler metadata for interaction replies.
 */
export type InteractionReplyHandler = { kind: InteractionReplyHandlerKind; requestId: string }

/**
 * Permission request data.
 */
export type PermissionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; permission: string; patterns: string[]; metadata: JsonValue; always: string[]; autoAccepted: boolean; tool?: ToolReference | null }

/**
 * Question request data.
 */
export type QuestionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; questions: QuestionItem[]; tool?: ToolReference | null }

/**
 * Payload for usage telemetry session update (generic, not provider-specific).
 */
export type UsageTelemetryData = { sessionId: string; eventId?: string | null; 
/**
 * Scope of the telemetry (e.g. "step", later "turn").
 */
scope?: string; costUsd?: number | null; tokens?: UsageTelemetryTokens; sourceModelId?: string | null; timestampMs?: number | null; 
/**
 * Context window size reported by the agent (e.g. from usage_update `size` field).
 */
contextWindowSize?: number | null }

/**
 * Token counts for usage telemetry (generic, adapter-agnostic).
 */
export type UsageTelemetryTokens = { total?: number | null; input?: number | null; output?: number | null; cacheRead?: number | null; cacheWrite?: number | null; reasoning?: number | null }

/**
 * Todo item status.
 */
export type TodoStatus = "pending" | "in_progress" | "completed" | "cancelled"

/**
 * Todo item.
 */
export type TodoItem = { content: string; activeForm: string; status: TodoStatus; startedAt?: number | null; completedAt?: number | null; duration?: number | null }

/**
 * Semantic todo update operation derived from provider tool calls.
 */
export type TodoUpdateOperation = "replace" | "upsert" | "set_status" | "set_status_by_filter"

/**
 * Canonical todo update payload, independent from provider transport details.
 */
export type TodoUpdate = { operation: TodoUpdateOperation; items?: TodoItem[] | null; fromStatuses?: TodoStatus[] | null; toStatus?: TodoStatus | null }

export type TranscriptEntryRole = "user" | "assistant" | "tool" | "error"

export type TranscriptSegment = { kind: "text"; segmentId: string; text: string }

export type TranscriptEntry = { entryId: string; role: TranscriptEntryRole; segments: TranscriptSegment[] }

export type TranscriptSnapshot = { revision: number; entries: TranscriptEntry[] }

export type TranscriptDeltaOperation = { kind: "appendEntry"; entry: TranscriptEntry } | { kind: "appendSegment"; entryId: string; role: TranscriptEntryRole; segment: TranscriptSegment } | { kind: "replaceSnapshot"; snapshot: TranscriptSnapshot }

export type TranscriptDelta = { eventSeq: number; sessionId: string; snapshotRevision: number; operations: TranscriptDeltaOperation[] }

/**
 * Marker enum identifying the domain event kind.
 * 
 * Kept as a flat string enum for backward-compatible discrimination
 * in frontend subscribers (`event.kind === "..."` comparisons).
 * Typed payload data is carried in [`SessionDomainEvent::payload`].
 */
export type SessionDomainEventKind = "session_identity_resolved" | "session_connected" | "session_disconnected" | "session_config_changed" | "turn_started" | "turn_completed" | "turn_failed" | "turn_cancelled" | "user_message_segment_appended" | "assistant_message_segment_appended" | "assistant_thought_segment_appended" | "operation_upserted" | "operation_child_linked" | "operation_completed" | "interaction_upserted" | "interaction_resolved" | "interaction_cancelled" | "usage_telemetry_updated" | "todo_state_updated"

/**
 * Typed payload carried by a canonical domain event.
 * 
 * Each variant corresponds to a [`SessionDomainEventKind`] and carries the
 * structured data that downstream reducers and projections need.  Consumers
 * can switch on `event.kind` for quick discrimination and access the typed
 * payload via `event.payload` when richer data is required.
 */
export type SessionDomainEventPayload = { kind: "session_identity_resolved"; resolved_provider_session_id: string } | { kind: "session_connected" } | { kind: "session_disconnected" } | { kind: "session_config_changed" } | { kind: "turn_started"; turn_id: string } | { kind: "turn_completed"; turn_id: string | null } | { kind: "turn_failed"; turn_id: string | null; error_message: string } | { kind: "turn_cancelled"; turn_id: string | null } | { kind: "user_message_segment_appended"; message_id: string; part_id: string | null; text: string } | { kind: "assistant_message_segment_appended"; message_id: string; part_id: string | null; text: string } | { kind: "assistant_thought_segment_appended"; message_id: string; part_id: string | null; text: string } | { kind: "operation_upserted"; operation_id: string; tool_call_id: string; tool_name: string; tool_kind: ToolKind; status: ToolCallStatus; parent_operation_id: string | null } | { kind: "operation_child_linked"; parent_operation_id: string; child_operation_id: string } | { kind: "operation_completed"; operation_id: string; tool_call_id: string; status: ToolCallStatus } | { kind: "interaction_upserted"; interaction_id: string; interaction_kind: InteractionKind } | { kind: "interaction_resolved"; interaction_id: string } | { kind: "interaction_cancelled"; interaction_id: string } | { kind: "usage_telemetry_updated"; data: UsageTelemetryData } | { kind: "todo_state_updated"; update: TodoUpdate }

/**
 * Canonical domain event envelope.
 * 
 * `kind` identifies the event type for quick string-based discrimination.
 * `payload` carries typed structured data — `None` only for events where
 * payloads are not yet wired at the emission site.
 */
export type SessionDomainEvent = { event_id: string; seq: number; session_id: string; provider_session_id: string | null; occurred_at_ms: number; causation_id: string | null; kind: SessionDomainEventKind; payload?: SessionDomainEventPayload | null }

export type SessionTurnState = "Idle" | "Running" | "Completed" | "Failed"

export type SessionSnapshot = { session_id: string; agent_id: CanonicalAgentId | null; last_event_seq: number; turn_state: SessionTurnState; message_count: number; last_agent_message_id: string | null; active_tool_call_ids: string[]; completed_tool_call_ids: string[]; active_turn_failure?: TurnFailureSnapshot | null; last_terminal_turn_id?: string | null }

export type OperationSnapshot = { id: string; session_id: string; tool_call_id: string; name: string; kind: ToolKind | null; status: ToolCallStatus; title: string | null; arguments: ToolArguments; progressive_arguments: ToolArguments | null; result: JsonValue | null; command: string | null; normalized_todos: TodoItem[] | null; parent_tool_call_id: string | null; parent_operation_id: string | null; child_tool_call_ids: string[]; child_operation_ids: string[] }

export type InteractionKind = "Permission" | "Question" | "PlanApproval"

export type InteractionState = "Pending" | "Approved" | "Rejected" | "Answered"

export type PlanApprovalSource = "CreatePlan" | "ExitPlanMode"

export type InteractionPayload = { Permission: PermissionData } | { Question: QuestionData } | { PlanApproval: { source: PlanApprovalSource } }

export type InteractionResponse = { kind: "permission"; accepted: boolean; option_id?: string | null; reply?: string | null } | { kind: "question"; answers: JsonValue } | { kind: "plan_approval"; approved: boolean }

export type InteractionSnapshot = { id: string; session_id: string; kind: InteractionKind; state: InteractionState; json_rpc_request_id: number | null; reply_handler: InteractionReplyHandler | null; tool_reference: ToolReference | null; responded_at_event_seq: number | null; response: InteractionResponse | null; payload: InteractionPayload }

/**
 * Turn error severity.
 */
export type TurnErrorKind = "recoverable" | "fatal"

/**
 * Turn error source.
 */
export type TurnErrorSource = "json_rpc" | "transport" | "process" | "unknown"

export type TurnFailureSnapshot = { turn_id: string | null; message: string; code?: string | null; kind: TurnErrorKind; source: TurnErrorSource }

export type LifecycleStatus = "reserved" | "activating" | "ready" | "reconnecting" | "detached" | "failed" | "archived"

export type DetachedReason = "restoredRequiresAttach" | "reconnectExhausted" | "abandonedInFlight" | "legacyAmbiguousRestore"

export type FailureReason = "deterministicRestoreFault" | "activationFailed" | "resumeFailed" | "providerSessionMismatch" | "corruptedPersistedState" | "explicitErrorHandlingRequired" | "legacyIrrecoverable"

export type LifecycleState = { status: LifecycleStatus; detachedReason?: DetachedReason | null; failureReason?: FailureReason | null; errorMessage?: string | null }

export type LifecycleCheckpoint = {
/**
 * Older persisted checkpoints may omit this field; treat as current version for migration.
 */
schemaVersion?: number; graphRevision: number; lifecycle: LifecycleState; capabilities: SessionGraphCapabilities }

export type SessionProjectionSnapshot = { session: SessionSnapshot | null; operations: OperationSnapshot[]; interactions: InteractionSnapshot[]; runtime?: LifecycleCheckpoint | null }

/**
 * Payload for the `error` outcome — persisted state was found but could not
 * be loaded or proven consistent.
 */
export type SessionOpenErrorReason = "parseFailure" | "internal"

/**
 * Payload for the `error` outcome — persisted state was found but could not
 * be loaded or proven consistent.
 */
export type SessionOpenError = { requestedSessionId: string; message: string; reason: SessionOpenErrorReason; retryable: boolean }

/**
 * Full payload for a `found` outcome.
 */
export type SessionOpenFound = { 
/**
 * The ID supplied by the caller (may be a provider-side alias).
 */
requestedSessionId: string; 
/**
 * The Acepe-local canonical session identifier.
 */
canonicalSessionId: string; 
/**
 * `true` when `requested_session_id` differs from `canonical_session_id`
 * (i.e. the caller supplied a provider-side alias that was resolved to a
 * different canonical ID).
 */
isAlias: boolean; 
/**
 * Proven journal cutoff.  `0` only when no journal events exist yet.
 */
lastEventSeq: number; 
/**
 * Canonical graph frontier at the proven cutoff.
 * 
 * During the compatibility window this may still be seeded from persisted
 * state that mirrors `last_event_seq`, but open/materialization paths must
 * carry it explicitly instead of re-deriving graph lineage from delivery.
 */
graphRevision: number; 
/**
 * Single-use attach token (UUID string).  All hub events for this session
 * published after this token is armed are buffered in the `event_hub`
 * reservation until the token is claimed (Unit 3) or expires after 30 s
 * of inactivity.
 */
openToken: string; agentId: CanonicalAgentId; projectPath: string; worktreePath: string | null; sourcePath: string | null; transcriptSnapshot: TranscriptSnapshot; sessionTitle: string; operations: OperationSnapshot[]; interactions: InteractionSnapshot[]; turnState: SessionTurnState; messageCount: number; activeTurnFailure?: TurnFailureSnapshot | null; lastTerminalTurnId?: string | null }

/**
 * Payload for the `missing` outcome — no persisted content was found for the
 * requested session identifier.
 */
export type SessionOpenMissing = { requestedSessionId: string }

/**
 * The unified outcome of a session-open request.
 * 
 * Returned by every session entry point (new, resume, history open).  The
 * frontend MUST NOT fetch projection state separately after receiving a
 * `Found` result; everything needed before live connect begins is included.
 */
export type SessionOpenResult = 
/**
 * Session was found; all pre-connect state is fully populated.
 * 
 * `Box`ed to keep the enum size bounded — `SessionOpenFound` carries
 * the full projection snapshot, which is significantly larger than the
 * `Missing` and `Error` payloads.
 */
({ outcome: "found" } & SessionOpenFound) | ({ outcome: "missing" } & SessionOpenMissing) | ({ outcome: "error" } & SessionOpenError)

export type SessionGraphRevision = { graphRevision: number; transcriptRevision: number; lastEventSeq: number }

export type SessionGraphLifecycleStatus = "idle" | "connecting" | "ready" | "error"

export type SessionGraphLifecycle = { status: SessionGraphLifecycleStatus; errorMessage?: string | null; canReconnect: boolean }

export type SessionGraphCapabilities = { models?: SessionModelState | null; modes?: SessionModes | null; availableCommands?: AvailableCommand[]; configOptions?: ConfigOptionData[]; autonomousEnabled?: boolean }

export type SessionGraphActivityKind = "awaiting_model" | "running_operation" | "waiting_for_user" | "paused" | "error" | "idle"

export type SessionGraphActivity = { kind: SessionGraphActivityKind; activeOperationCount: number; activeSubagentCount: number; dominantOperationId?: string | null; blockingInteractionId?: string | null }

export type CapabilityPreviewState = "canonical" | "pending" | "failed" | "partial" | "stale"

export type SessionStateGraph = { requestedSessionId: string; canonicalSessionId: string; isAlias: boolean; agentId: CanonicalAgentId; projectPath: string; worktreePath?: string | null; sourcePath?: string | null; revision: SessionGraphRevision; transcriptSnapshot: TranscriptSnapshot; operations: OperationSnapshot[]; interactions: InteractionSnapshot[]; turnState: SessionTurnState; messageCount: number; activeTurnFailure?: TurnFailureSnapshot | null; lastTerminalTurnId?: string | null; lifecycle: SessionGraphLifecycle; activity: SessionGraphActivity; capabilities: SessionGraphCapabilities }

export type SessionStateSnapshotMaterialization = { graph: SessionStateGraph }

export type SessionStateDelta = { fromRevision: SessionGraphRevision; toRevision: SessionGraphRevision; transcriptOperations: TranscriptDeltaOperation[]; changedFields?: string[] }

export type SessionStatePayload = { kind: "snapshot"; graph: SessionStateGraph } | { kind: "delta"; delta: SessionStateDelta } | { kind: "lifecycle"; lifecycle: SessionGraphLifecycle; revision: SessionGraphRevision } | { kind: "capabilities"; capabilities: SessionGraphCapabilities; revision: SessionGraphRevision; pending_mutation_id?: string | null; preview_state: CapabilityPreviewState } | { kind: "telemetry"; telemetry: UsageTelemetryData; revision: SessionGraphRevision }

export type SessionStateEnvelope = { sessionId: string; graphRevision: number; lastEventSeq: number; payload: SessionStatePayload }


export type ProviderBrand = "claude-code" | "copilot" | "cursor" | "opencode" | "codex" | "custom";

export type ProviderVariantGroup = "plain" | "reasoningEffort";

export type PreconnectionSlashMode = "startupGlobal" | "projectScoped" | "unsupported";

export type ProviderMetadataProjection = {
	providerBrand: ProviderBrand;
	displayName: string;
	displayOrder: number;
	supportsModelDefaults: boolean;
	variantGroup: ProviderVariantGroup;
	defaultAlias?: string;
	reasoningEffortSupport: boolean;
	preconnectionSlashMode: PreconnectionSlashMode;
};

export type ModelsForDisplayWithProvider = ModelsForDisplay;

export const BUILTIN_PROVIDER_METADATA_BY_AGENT_ID: Record<string, ProviderMetadataProjection> = {
	"claude-code": {
		providerBrand: "claude-code",
		displayName: "Claude Code",
		displayOrder: 10,
		supportsModelDefaults: true,
		variantGroup: "plain",
		defaultAlias: "default",
		reasoningEffortSupport: false,
		preconnectionSlashMode: "startupGlobal",
	},
	copilot: {
		providerBrand: "copilot",
		displayName: "GitHub Copilot",
		displayOrder: 30,
		supportsModelDefaults: false,
		variantGroup: "plain",
		defaultAlias: undefined,
		reasoningEffortSupport: false,
		preconnectionSlashMode: "projectScoped",
	},
	cursor: {
		providerBrand: "cursor",
		displayName: "Cursor",
		displayOrder: 20,
		supportsModelDefaults: true,
		variantGroup: "plain",
		defaultAlias: "auto",
		reasoningEffortSupport: false,
		preconnectionSlashMode: "startupGlobal",
	},
	opencode: {
		providerBrand: "opencode",
		displayName: "OpenCode",
		displayOrder: 40,
		supportsModelDefaults: true,
		variantGroup: "plain",
		defaultAlias: undefined,
		reasoningEffortSupport: false,
		preconnectionSlashMode: "projectScoped",
	},
	codex: {
		providerBrand: "codex",
		displayName: "Codex",
		displayOrder: 50,
		supportsModelDefaults: true,
		variantGroup: "reasoningEffort",
		defaultAlias: undefined,
		reasoningEffortSupport: true,
		preconnectionSlashMode: "startupGlobal",
	},
};

function cloneProviderMetadataProjection(
	providerMetadata: ProviderMetadataProjection
): ProviderMetadataProjection {
	return {
		providerBrand: providerMetadata.providerBrand,
		displayName: providerMetadata.displayName,
		displayOrder: providerMetadata.displayOrder,
		supportsModelDefaults: providerMetadata.supportsModelDefaults,
		variantGroup: providerMetadata.variantGroup,
		defaultAlias: providerMetadata.defaultAlias,
		reasoningEffortSupport: providerMetadata.reasoningEffortSupport,
		preconnectionSlashMode: providerMetadata.preconnectionSlashMode,
	};
}

export function resolveProviderMetadataProjection(
	agentId: string,
	providerMetadata: ProviderMetadataProjection | null | undefined,
	fallbackDisplayName?: string
): ProviderMetadataProjection {
	if (providerMetadata) {
		return cloneProviderMetadataProjection(providerMetadata);
	}

	const builtInProviderMetadata = BUILTIN_PROVIDER_METADATA_BY_AGENT_ID[agentId];
	if (builtInProviderMetadata) {
		return cloneProviderMetadataProjection(builtInProviderMetadata);
	}

	return {
		providerBrand: "custom",
		displayName: fallbackDisplayName ?? agentId,
		displayOrder: 65535,
		supportsModelDefaults: false,
		variantGroup: "plain",
		defaultAlias: undefined,
		reasoningEffortSupport: false,
		preconnectionSlashMode: "unsupported",
	};
}

export function getProviderMetadataFromModelsDisplay(
	modelsDisplay: ModelsForDisplay | null | undefined
): ProviderMetadataProjection | null {
	return modelsDisplay?.presentation?.provider ?? null;
}

export function normalizeModelsForDisplay(
	agentId: string,
	modelsDisplay: ModelsForDisplay | null | undefined,
	fallbackDisplayName?: string,
	providerMetadataOverride?: ProviderMetadataProjection | null
): ModelsForDisplay | null {
	if (!modelsDisplay) {
		return null;
	}

	const providerMetadata = resolveProviderMetadataProjection(
		agentId,
		providerMetadataOverride ?? getProviderMetadataFromModelsDisplay(modelsDisplay),
		fallbackDisplayName
	);
	const presentation = modelsDisplay.presentation;
	const displayFamily =
		presentation?.displayFamily ??
		(providerMetadata.variantGroup === "reasoningEffort"
			? "codexReasoningEffort"
			: "providerGrouped");

	return {
		groups: modelsDisplay.groups,
		presentation: {
			displayFamily,
			usageMetrics: presentation?.usageMetrics ?? "spendAndContext",
			provider: providerMetadata,
		},
	};
}
