// This file was generated by specta. Do not edit this file manually.

// JsonValue represents any valid JSON value
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type AvailableModel = { modelId: string; name: string; description?: string | null }

export type AvailableMode = { id: string; name: string; description?: string | null }

/**
 * Command input hint.
 */
export type CommandInput = { 
/**
 * The hint can be a string or array in the protocol; we normalize to string.
 */
hint: string }

/**
 * Available command with metadata.
 */
export type AvailableCommand = { name: string; description: string; input?: CommandInput | null }

/**
 * Pre-computed model info for display. Frontend uses this directly.
 */
export type DisplayableModel = { modelId: string; displayName: string; description?: string | null }

/**
 * Generic group of models. Label can be provider, base model name, or empty.
 */
export type DisplayModelGroup = { label: string; models: DisplayableModel[] }

export type ModelDisplayFamily = "claudeLike" | "codexReasoningEffort" | "providerGrouped"

export type UsageMetricsPresentation = "contextWindowOnly" | "spendAndContext"

export type ModelPresentationMetadata = { displayFamily: ModelDisplayFamily; usageMetrics: UsageMetricsPresentation; provider?: ProviderMetadataProjection }

/**
 * Display-ready model structure. Single representation—flat = one group.
 */
export type ModelsForDisplay = { groups: DisplayModelGroup[]; presentation?: ModelPresentationMetadata }

export type SessionModelState = { availableModels?: AvailableModel[]; currentModelId?: string; modelsDisplay?: ModelsForDisplay; providerMetadata?: ProviderMetadataProjection }

export type SessionModes = { currentModeId?: string; availableModes?: AvailableMode[] }

/**
 * Configuration option value.
 */
export type ConfigOptionValue = { name: string; value: JsonValue; description?: string | null }

/**
 * Configuration option data.
 */
export type ConfigOptionData = { id: string; name: string; category: string; type: string; description?: string | null; currentValue?: JsonValue | null; options?: ConfigOptionValue[] }

export type NewSessionResponse = { sessionId: string; sequenceId?: number | null; models?: SessionModelState; modes?: SessionModes; availableCommands?: AvailableCommand[]; configOptions?: ConfigOptionData[] }

export type ResumeSessionResponse = { models?: SessionModelState; modes?: SessionModes; availableCommands?: AvailableCommand[]; configOptions?: ConfigOptionData[] }

/**
 * Canonical agent identifier enum.
 * 
 * This enum represents all valid agent types in the system.
 * Parsers set the enum directly based on their context (no normalization needed).
 */
export type CanonicalAgentId = "claude-code" | "copilot" | "cursor" | "opencode" | "codex" | "forge" | 
/**
 * Custom agent registered by user
 */
{ custom: string }

/**
 * Tool kind for routing to appropriate UI components.
 */
export type ToolKind = "read" | "edit" | "execute" | "search" | "glob" | "fetch" | "web_search" | "think" | "todo" | "question" | "task" | "task_output" | "skill" | "move" | "delete" | "enter_plan_mode" | "exit_plan_mode" | "create_plan" | "tool_search" | "browser" | "other"

/**
 * Tool call status.
 */
export type ToolCallStatus = "pending" | "in_progress" | "completed" | "failed"

export type ChunkAggregationHint = "boundaryCarryover"

/**
 * A single canonical file delta within an Edit tool call.
 * 
 * A single `Edit` tool call may touch multiple files (e.g. OpenCode patch text
 * or Codex changes maps). Each entry must declare its semantic edit variant
 * explicitly instead of relying on a bag of optional transport-era fields.
 */
export type EditDelta = { type: "replaceText"; file_path?: string | null; move_from?: string | null; old_text?: string | null; new_text?: string | null } | { type: "writeFile"; file_path?: string | null; move_from?: string | null; previous_content?: string | null; content?: string | null } | { type: "deleteFile"; file_path?: string | null; old_text?: string | null }

/**
 * Tool arguments discriminated by tool kind.
 * Each variant contains exactly the fields needed for that tool type.
 */
export type ToolArguments = { kind: "read"; file_path?: string | null } | 
/**
 * Edit tool arguments.
 * 
 * `edits` is always a non-empty Vec. Single-file edits have exactly one entry;
 * multi-file edits (OpenCode `patch`, Codex multi-entry `changes` map) have N entries.
 */
{ kind: "edit"; edits: EditDelta[] } | { kind: "execute"; command?: string | null } | { kind: "search"; query?: string | null; file_path?: string | null } | { kind: "glob"; pattern?: string | null; path?: string | null } | { kind: "fetch"; url?: string | null } | { kind: "webSearch"; query?: string | null } | { kind: "think"; description?: string | null; prompt?: string | null; subagent_type?: string | null; skill?: string | null; skill_args?: string | null; raw?: JsonValue | null } | { kind: "taskOutput"; task_id?: string | null; timeout?: number | null } | { kind: "move"; from?: string | null; to?: string | null } | { kind: "delete"; file_path?: string | null; file_paths?: string[] | null } | { kind: "planMode"; mode?: string | null } | { kind: "toolSearch"; query?: string | null; max_results?: number | null } | { kind: "browser"; raw: JsonValue } | { kind: "other"; raw: JsonValue }

/**
 * Tool reference for permission/question requests.
 */
export type ToolReference = { messageId: string; callId: string }

/**
 * Question option.
 */
export type QuestionOption = { label: string; description: string }

/**
 * Question item.
 */
export type QuestionItem = { question: string; header: string; options: QuestionOption[]; multiSelect: boolean }

/**
 * Explicit reply routing metadata for a canonical interaction.
 */
export type InteractionReplyHandlerKind = "json_rpc" | "http"

/**
 * Backend-owned reply handler metadata for interaction replies.
 */
export type InteractionReplyHandler = { kind: InteractionReplyHandlerKind; requestId: string }

/**
 * Permission request data.
 */
export type PermissionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; permission: string; patterns: string[]; metadata: JsonValue; always: string[]; autoAccepted: boolean; tool?: ToolReference | null }

/**
 * Question request data.
 */
export type QuestionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; questions: QuestionItem[]; tool?: ToolReference | null }

export type SessionDomainEventKind = "session_identity_resolved" | "session_connected" | "session_disconnected" | "session_config_changed" | "turn_started" | "turn_completed" | "turn_failed" | "turn_cancelled" | "user_message_segment_appended" | "assistant_message_segment_appended" | "assistant_thought_segment_appended" | "operation_upserted" | "operation_child_linked" | "operation_completed" | "interaction_upserted" | "interaction_resolved" | "interaction_cancelled" | "usage_telemetry_updated" | "todo_state_updated"

export type SessionDomainEvent = { event_id: string; seq: number; session_id: string; provider_session_id: string | null; occurred_at_ms: number; causation_id: string | null; kind: SessionDomainEventKind }

export type SessionTurnState = "Idle" | "Running" | "Completed" | "Failed"

export type SessionSnapshot = { session_id: string; agent_id: CanonicalAgentId | null; last_event_seq: number; turn_state: SessionTurnState; message_count: number; last_agent_message_id: string | null; active_tool_call_ids: string[]; completed_tool_call_ids: string[] }

export type OperationSnapshot = { id: string; session_id: string; tool_call_id: string; name: string; kind: ToolKind | null; status: ToolCallStatus; title: string | null; arguments: ToolArguments; progressive_arguments: ToolArguments | null; result: JsonValue | null; command: string | null; parent_tool_call_id: string | null; parent_operation_id: string | null; child_tool_call_ids: string[]; child_operation_ids: string[] }

export type InteractionKind = "Permission" | "Question" | "PlanApproval"

export type InteractionState = "Pending" | "Approved" | "Rejected" | "Answered"

export type PlanApprovalSource = "CreatePlan" | "ExitPlanMode"

export type InteractionPayload = { Permission: PermissionData } | { Question: QuestionData } | { PlanApproval: { source: PlanApprovalSource } }

export type InteractionResponse = { kind: "permission"; accepted: boolean; option_id?: string | null; reply?: string | null } | { kind: "question"; answers: JsonValue } | { kind: "plan_approval"; approved: boolean }

export type InteractionSnapshot = { id: string; session_id: string; kind: InteractionKind; state: InteractionState; json_rpc_request_id: number | null; reply_handler: InteractionReplyHandler | null; tool_reference: ToolReference | null; responded_at_event_seq: number | null; response: InteractionResponse | null; payload: InteractionPayload }

export type SessionProjectionSnapshot = { session: SessionSnapshot | null; operations: OperationSnapshot[]; interactions: InteractionSnapshot[] }


export type ProviderBrand = "claude-code" | "copilot" | "cursor" | "opencode" | "codex" | "custom";

export type ProviderVariantGroup = "plain" | "reasoningEffort";

export type PreconnectionSlashMode = "startupGlobal" | "projectScoped" | "unsupported";

export type ProviderMetadataProjection = {
	providerBrand: ProviderBrand;
	displayName: string;
	displayOrder: number;
	supportsModelDefaults: boolean;
	variantGroup: ProviderVariantGroup;
	defaultAlias?: string;
	reasoningEffortSupport: boolean;
	preconnectionSlashMode: PreconnectionSlashMode;
};

export type ModelsForDisplayWithProvider = ModelsForDisplay;

export const BUILTIN_PROVIDER_METADATA_BY_AGENT_ID: Record<string, ProviderMetadataProjection> = {
	"claude-code": {
		providerBrand: "claude-code",
		displayName: "Claude Code",
		displayOrder: 10,
		supportsModelDefaults: true,
		variantGroup: "plain",
		defaultAlias: "default",
		reasoningEffortSupport: false,
		preconnectionSlashMode: "startupGlobal",
	},
	copilot: {
		providerBrand: "copilot",
		displayName: "GitHub Copilot",
		displayOrder: 30,
		supportsModelDefaults: false,
		variantGroup: "plain",
		defaultAlias: undefined,
		reasoningEffortSupport: false,
		preconnectionSlashMode: "projectScoped",
	},
	cursor: {
		providerBrand: "cursor",
		displayName: "Cursor",
		displayOrder: 20,
		supportsModelDefaults: true,
		variantGroup: "plain",
		defaultAlias: "auto",
		reasoningEffortSupport: false,
		preconnectionSlashMode: "startupGlobal",
	},
	opencode: {
		providerBrand: "opencode",
		displayName: "OpenCode",
		displayOrder: 40,
		supportsModelDefaults: true,
		variantGroup: "plain",
		defaultAlias: undefined,
		reasoningEffortSupport: false,
		preconnectionSlashMode: "projectScoped",
	},
	codex: {
		providerBrand: "codex",
		displayName: "Codex",
		displayOrder: 50,
		supportsModelDefaults: true,
		variantGroup: "reasoningEffort",
		defaultAlias: undefined,
		reasoningEffortSupport: true,
		preconnectionSlashMode: "startupGlobal",
	},
};

function cloneProviderMetadataProjection(
	providerMetadata: ProviderMetadataProjection
): ProviderMetadataProjection {
	return {
		providerBrand: providerMetadata.providerBrand,
		displayName: providerMetadata.displayName,
		displayOrder: providerMetadata.displayOrder,
		supportsModelDefaults: providerMetadata.supportsModelDefaults,
		variantGroup: providerMetadata.variantGroup,
		defaultAlias: providerMetadata.defaultAlias,
		reasoningEffortSupport: providerMetadata.reasoningEffortSupport,
		preconnectionSlashMode: providerMetadata.preconnectionSlashMode,
	};
}

export function resolveProviderMetadataProjection(
	agentId: string,
	providerMetadata: ProviderMetadataProjection | null | undefined,
	fallbackDisplayName?: string
): ProviderMetadataProjection {
	if (providerMetadata) {
		return cloneProviderMetadataProjection(providerMetadata);
	}

	const builtInProviderMetadata = BUILTIN_PROVIDER_METADATA_BY_AGENT_ID[agentId];
	if (builtInProviderMetadata) {
		return cloneProviderMetadataProjection(builtInProviderMetadata);
	}

	return {
		providerBrand: "custom",
		displayName: fallbackDisplayName ?? agentId,
		displayOrder: 65535,
		supportsModelDefaults: false,
		variantGroup: "plain",
		defaultAlias: undefined,
		reasoningEffortSupport: false,
		preconnectionSlashMode: "unsupported",
	};
}

export function getProviderMetadataFromModelsDisplay(
	modelsDisplay: ModelsForDisplay | null | undefined
): ProviderMetadataProjection | null {
	return modelsDisplay?.presentation?.provider ?? null;
}

export function normalizeModelsForDisplay(
	agentId: string,
	modelsDisplay: ModelsForDisplay | null | undefined,
	fallbackDisplayName?: string,
	providerMetadataOverride?: ProviderMetadataProjection | null
): ModelsForDisplay | null {
	if (!modelsDisplay) {
		return null;
	}

	const providerMetadata = resolveProviderMetadataProjection(
		agentId,
		providerMetadataOverride ?? getProviderMetadataFromModelsDisplay(modelsDisplay),
		fallbackDisplayName
	);
	const presentation = modelsDisplay.presentation;
	const displayFamily =
		presentation?.displayFamily ??
		(providerMetadata.variantGroup === "reasoningEffort"
			? "codexReasoningEffort"
			: "providerGrouped");

	return {
		groups: modelsDisplay.groups,
		presentation: {
			displayFamily,
			usageMetrics: presentation?.usageMetrics ?? "spendAndContext",
			provider: providerMetadata,
		},
	};
}

