// This file was generated by specta. Do not edit this file manually.

/**
 * Old and new file content for diff display.
 */
export type FileDiffContent = {
/**
 * Content from previous checkpoint. None if this is a new file in the timeline.
 */
oldContent: string | null;
/**
 * Content at the current checkpoint.
 */
newContent: string }
