// This file was generated by specta. Do not edit this file manually.

// JsonValue represents any valid JSON value
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

/**
 * Canonical agent identifier enum.
 *
 * This enum represents all valid agent types in the system.
 * Parsers set the enum directly based on their context (no normalization needed).
 */
export type CanonicalAgentId = "claude-code" | "copilot" | "cursor" | "opencode" | "codex" | "forge" |
/**
 * Custom agent registered by user
 */
{ custom: string }

export type SessionLifecycleState = "created" | "persisted"

export type HistoryEntry = {
/**
 * Database ID (UUID)
 */
id: string; display: string; timestamp: number; project: string; sessionId: string; pastedContents?: JsonValue; agentId: CanonicalAgentId; updatedAt: number;
/**
 * Source file path for direct retrieval (JSON transcript, store.db, or state.vscdb)
 */
sourcePath?: string | null;
/**
 * Parent session ID for subsessions (OpenCode only).
 */
parentId?: string | null;
/**
 * Optional worktree path when session operates in a git worktree.
 * Used for correct path conversion when creating checkpoints.
 */
worktreePath?: string | null;
/**
 * Associated pull request number when session references a PR (e.g. from OpenCode).
 */
prNumber?: number | null;
/**
 * Ownership mode for the session-linked PR.
 */
prLinkMode?: string | null;
/**
 * Whether the worktree path stored for this session no longer exists on disk.
 */
worktreeDeleted?: boolean | null; sessionLifecycleState?: SessionLifecycleState | null;
/**
 * Per-project sequence ID for Acepe-native sessions (None for scanned sessions).
 */
sequenceId?: number | null }

/**
 * Response wrapper for get_startup_sessions.
 *
 * Carries the hydrated session entries plus a mapping from any requested
 * alias IDs (provider_session_id values) to their canonical Acepe session IDs.
 * This allows the frontend to remap panel session references before validation.
 */
export type StartupSessionsResponse = { entries: HistoryEntry[];
/**
 * Maps requested alias ID -> canonical session ID for sessions that were
 * matched by `provider_session_id` rather than the primary `id`.
 */
aliasRemaps: Partial<{ [key in string]: string }> }
