// This file was generated from Rust command metadata. Do not edit this file manually.

export const COMMANDS = {
  "acp": {
    "initialize": "acp_initialize",
    "new_session": "acp_new_session",
    "resume_session": "acp_resume_session",
    "fork_session": "acp_fork_session",
    "set_model": "acp_set_model",
    "set_mode": "acp_set_mode",
    "set_session_autonomous": "acp_set_session_autonomous",
    "set_config_option": "acp_set_config_option",
    "send_prompt": "acp_send_prompt",
    "cancel": "acp_cancel",
    "reply_interaction": "acp_reply_interaction",
    "respond_inbound_request": "acp_respond_inbound_request",
    "get_event_bridge_info": "acp_get_event_bridge_info",
    "get_session_state": "acp_get_session_state",
    "list_agents": "acp_list_agents",
    "list_preconnection_capabilities": "acp_list_preconnection_capabilities",
    "list_preconnection_commands": "acp_list_preconnection_commands",
    "install_agent": "acp_install_agent",
    "uninstall_agent": "acp_uninstall_agent",
    "close_session": "acp_close_session",
    "register_custom_agent": "acp_register_custom_agent"
  },
  "fs": {
    "read_text_file": "acp_read_text_file",
    "write_text_file": "acp_write_text_file"
  },
  "history": {
    "get_cache_stats": "get_cache_stats",
    "invalidate_history_cache": "invalidate_history_cache",
    "reset_cache_stats": "reset_cache_stats",
    "get_index_status": "get_index_status",
    "reindex_sessions": "reindex_sessions",
    "get_session_open_result": "get_session_open_result",
    "audit_session_load_timing": "audit_session_load_timing",
    "set_session_worktree_path": "set_session_worktree_path",
    "set_session_pr_number": "set_session_pr_number",
    "set_session_title": "set_session_title",
    "get_unified_plan": "get_unified_plan",
    "scan_project_sessions": "scan_project_sessions",
    "get_startup_sessions": "get_startup_sessions",
    "discover_all_projects_with_sessions": "discover_all_projects_with_sessions",
    "list_all_project_paths": "list_all_project_paths",
    "count_sessions_for_project": "count_sessions_for_project"
  },
  "cursor_history": {
    "has_cursor_history": "has_cursor_history",
    "is_cursor_installed": "is_cursor_installed"
  },
  "opencode_history": {
    "get_opencode_history": "get_opencode_history",
    "get_opencode_sessions_for_project": "get_opencode_sessions_for_project"
  },
  "storage": {
    "get_projects": "get_projects",
    "get_recent_projects": "get_recent_projects",
    "get_project_count": "get_project_count",
    "get_missing_project_paths": "get_missing_project_paths",
    "import_project": "import_project",
    "add_project": "add_project",
    "update_project_color": "update_project_color",
    "update_project_icon": "update_project_icon",
    "update_project_order": "update_project_order",
    "remove_project": "remove_project",
    "browse_project": "browse_project",
    "browse_project_icon": "browse_project_icon",
    "list_project_images": "list_project_images",
    "get_project_acepe_config": "get_project_acepe_config",
    "save_project_acepe_config": "save_project_acepe_config",
    "backfill_project_icons": "backfill_project_icons",
    "save_api_key": "save_api_key",
    "delete_api_key": "delete_api_key",
    "get_custom_keybindings": "get_custom_keybindings",
    "save_custom_keybindings": "save_custom_keybindings",
    "get_streaming_log_path": "get_streaming_log_path",
    "get_session_file_path": "get_session_file_path",
    "save_user_setting": "save_user_setting",
    "get_user_setting": "get_user_setting",
    "save_session_review_state": "save_session_review_state",
    "get_session_review_state": "get_session_review_state",
    "delete_session_review_state": "delete_session_review_state",
    "save_thread_list_settings": "save_thread_list_settings",
    "get_thread_list_settings": "get_thread_list_settings",
    "request_destructive_confirmation_token": "request_destructive_confirmation_token",
    "reset_database": "reset_database",
    "open_in_finder": "open_in_finder",
    "open_streaming_log": "open_streaming_log"
  },
  "file_index": {
    "get_project_files": "get_project_files",
    "get_project_git_status": "get_project_git_status",
    "get_project_git_status_summary": "get_project_git_status_summary",
    "get_project_git_overview_summary": "get_project_git_overview_summary",
    "invalidate_project_files": "invalidate_project_files",
    "read_file_content": "read_file_content",
    "resolve_file_path": "resolve_file_path",
    "get_file_diff": "get_file_diff",
    "revert_file_content": "revert_file_content",
    "read_image_as_base64": "read_image_as_base64",
    "copy_file": "copy_file",
    "create_directory": "create_directory",
    "create_file": "create_file",
    "delete_path": "delete_path",
    "rename_path": "rename_path",
    "search_project_files_for_explorer": "search_project_files_for_explorer",
    "get_file_explorer_preview": "get_file_explorer_preview"
  },
  "terminal": {
    "create": "terminal_create",
    "output": "terminal_output",
    "wait_for_exit": "terminal_wait_for_exit",
    "kill": "terminal_kill",
    "release": "terminal_release",
    "get_default_shell": "get_default_shell"
  },
  "git": {
    "clone": "git_clone",
    "browse_destination": "browse_clone_destination",
    "init": "git_init",
    "is_repo": "git_is_repo",
    "current_branch": "git_current_branch",
    "list_branches": "git_list_branches",
    "checkout_branch": "git_checkout_branch",
    "has_uncommitted_changes": "git_has_uncommitted_changes",
    "worktree_create": "git_worktree_create",
    "prepare_worktree_session_launch": "git_prepare_worktree_session_launch",
    "discard_prepared_worktree_session_launch": "git_discard_prepared_worktree_session_launch",
    "worktree_remove": "git_worktree_remove",
    "worktree_reset": "git_worktree_reset",
    "worktree_list": "git_worktree_list",
    "worktree_rename": "git_worktree_rename",
    "worktree_disk_size": "git_worktree_disk_size",
    "collect_ship_context": "git_collect_ship_context",
    "pr_details": "git_pr_details",
    "pr_checks": "git_pr_checks",
    "merge_pr": "git_merge_pr",
    "get_open_pr_for_branch": "get_open_pr_for_branch",
    "watch_head": "git_watch_head",
    "load_worktree_config": "load_worktree_config",
    "run_worktree_setup": "run_worktree_setup",
    "save_worktree_config": "save_worktree_config",
    "panel_status": "git_panel_status",
    "diff_stats": "git_diff_stats",
    "stage_files": "git_stage_files",
    "unstage_files": "git_unstage_files",
    "stage_all": "git_stage_all",
    "discard_changes": "git_discard_changes",
    "commit": "git_commit",
    "push": "git_push",
    "pull": "git_pull",
    "fetch": "git_fetch",
    "remote_status": "git_remote_status",
    "stash_list": "git_stash_list",
    "stash_pop": "git_stash_pop",
    "stash_drop": "git_stash_drop",
    "stash_save": "git_stash_save",
    "log": "git_log",
    "create_branch": "git_create_branch",
    "delete_branch": "git_delete_branch",
    "run_stacked_action": "git_run_stacked_action"
  },
  "checkpoint": {
    "create": "checkpoint_create",
    "list": "checkpoint_list",
    "get_file_content": "checkpoint_get_file_content",
    "get_file_diff_content": "checkpoint_get_file_diff_content",
    "revert": "checkpoint_revert",
    "revert_file": "checkpoint_revert_file",
    "get_file_snapshots": "checkpoint_get_file_snapshots"
  },
  "skills": {
    "list_tree": "skills_list_tree",
    "list_agent_skills": "skills_list_agent_skills",
    "get": "skills_get",
    "create": "skills_create",
    "update": "skills_update",
    "delete": "skills_delete",
    "copy_to": "skills_copy_to",
    "start_watching": "skills_start_watching",
    "stop_watching": "skills_stop_watching",
    "list_plugins": "skills_list_plugins",
    "list_plugin_skills": "skills_list_plugin_skills",
    "get_plugin_skill": "skills_get_plugin_skill",
    "copy_plugin_skill_to_agent": "skills_copy_plugin_skill_to_agent",
    "library_list_skills": "library_skills_list",
    "library_list_skills_with_sync": "library_skills_list_with_sync",
    "library_get_skill": "library_skill_get",
    "library_create_skill": "library_skill_create",
    "library_update_skill": "library_skill_update",
    "library_delete_skill": "library_skill_delete",
    "library_get_sync_targets": "library_skill_get_sync_targets",
    "library_set_sync_target": "library_skill_set_sync_target",
    "library_sync_skill": "library_skill_sync",
    "library_sync_all": "library_sync_all",
    "library_is_empty": "library_is_empty",
    "library_import_existing": "library_import_existing",
    "library_get_skill_folder_path": "library_skill_get_folder_path",
    "library_delete_skill_from_agents": "library_skill_delete_from_agents"
  },
  "sql_studio": {
    "list_connections": "sql_studio_list_connections",
    "get_connection": "sql_studio_get_connection",
    "save_connection": "sql_studio_save_connection",
    "delete_connection": "sql_studio_delete_connection",
    "pick_sqlite_file": "sql_studio_pick_sqlite_file",
    "test_connection": "sql_studio_test_connection",
    "test_connection_input": "sql_studio_test_connection_input",
    "list_schema": "sql_studio_list_schema",
    "execute_query": "sql_studio_execute_query",
    "explore_table": "sql_studio_explore_table",
    "update_table_cell": "sql_studio_update_table_cell"
  },
  "github": {
    "fetch_commit_diff": "fetch_commit_diff",
    "fetch_pr_diff": "fetch_pr_diff",
    "get_github_repo_context": "get_github_repo_context",
    "git_working_file_diff": "git_working_file_diff",
    "list_pull_requests": "list_pull_requests",
    "check_github_auth": "check_github_auth",
    "create_github_issue": "create_github_issue",
    "create_issue_comment": "create_issue_comment",
    "get_github_issue": "get_github_issue",
    "list_github_issues": "list_github_issues",
    "list_issue_comments": "list_issue_comments",
    "search_github_issues": "search_github_issues",
    "toggle_comment_reaction": "toggle_comment_reaction",
    "toggle_issue_reaction": "toggle_issue_reaction"
  },
  "browser_webview": {
    "open": "open_browser_webview",
    "close": "close_browser_webview",
    "navigate": "navigate_browser_webview",
    "reload": "reload_browser_webview",
    "back": "browser_webview_back",
    "forward": "browser_webview_forward",
    "get_url": "get_browser_webview_url",
    "show": "show_browser_webview",
    "hide": "hide_browser_webview",
    "resize": "resize_browser_webview",
    "set_zoom": "set_browser_webview_zoom"
  },
  "voice": {
    "list_models": "voice_list_models",
    "list_languages": "voice_list_languages",
    "get_model_status": "voice_get_model_status",
    "download_model": "voice_download_model",
    "delete_model": "voice_delete_model",
    "load_model": "voice_load_model",
    "start_recording": "voice_start_recording",
    "stop_recording": "voice_stop_recording",
    "cancel_recording": "voice_cancel_recording"
  },
  "window": {
    "activate": "activate_window"
  }
} as const;

export type Commands = typeof COMMANDS;
export type AcpCommands = Commands["acp"];
export type FsCommands = Commands["fs"];
export type HistoryCommands = Commands["history"];
export type CursorHistoryCommands = Commands["cursor_history"];
export type OpenCodeHistoryCommands = Commands["opencode_history"];
export type StorageCommands = Commands["storage"];
export type FileIndexCommands = Commands["file_index"];
export type TerminalCommands = Commands["terminal"];
export type GitCommands = Commands["git"];
export type CheckpointCommands = Commands["checkpoint"];
export type SkillsCommands = Commands["skills"];
export type SqlStudioCommands = Commands["sql_studio"];
export type GitHubCommands = Commands["github"];
export type BrowserWebviewCommands = Commands["browser_webview"];
export type VoiceCommands = Commands["voice"];
export type WindowCommands = Commands["window"];
