// This file was generated by specta. Do not edit this file manually.

/**
 * ACP (Agent Client Protocol) command names
 */
export type AcpCommands = { initialize: string; new_session: string; resume_session: string; fork_session: string; set_model: string; set_mode: string; set_session_autonomous: string; send_prompt: string; cancel: string; list_agents: string; install_agent: string; uninstall_agent: string; get_capabilities: string }

/**
 * Session history command names (jsonl-backed session list and messages).
 */
export type SessionHistoryCommands = { get_session_history: string; get_session_messages: string; get_full_session: string; get_converted_session: string; get_cache_stats: string; invalidate_history_cache: string; reset_cache_stats: string }

/**
 * Storage command names
 */
export type StorageCommands = { save_conversation_metadata: string; get_conversation_metadata: string; get_all_conversation_metadata: string; delete_conversation_metadata: string; update_conversation_metadata: string; delete_conversation: string; open_in_finder: string; open_streaming_log: string; get_projects: string; get_recent_projects: string; get_project_count: string; get_missing_project_paths: string; import_project: string; add_project: string; update_project_color: string; update_project_icon: string; update_project_order: string; remove_project: string; browse_project: string; get_all_conversations: string; upsert_conversation: string; get_user_setting: string; save_user_setting: string; get_panel_layout: string; save_panel_layout: string; clear_panel_layout: string; get_thread_list_settings: string; save_thread_list_settings: string; get_api_key: string; save_api_key: string; delete_api_key: string; get_user_keybindings: string; save_user_keybinding: string; delete_user_keybinding: string; reset_keybindings_to_defaults: string }

/**
 * Cursor history command names
 */
export type CursorHistoryCommands = { get_cursor_history: string; get_cursor_session: string }

/**
 * GitHub integration command names
 */
export type GitHubCommands = { get_github_repo_context: string; list_pull_requests: string; fetch_commit_diff: string; fetch_pr_diff: string; git_working_file_diff: string }

/**
 * Voice command names
 */
export type VoiceCommands = { list_models: string; list_languages: string; get_model_status: string; download_model: string; delete_model: string; start_recording: string; stop_recording: string; cancel_recording: string; load_model: string }

/**
 * All command name constants grouped by category
 */
export type Commands = { acp: AcpCommands; session_history: SessionHistoryCommands; storage: StorageCommands; cursor_history: CursorHistoryCommands; github: GitHubCommands; voice: VoiceCommands }

export const COMMANDS: Commands = {
  "acp": {
    "initialize": "acp_initialize",
    "new_session": "acp_new_session",
    "resume_session": "acp_resume_session",
    "fork_session": "acp_fork_session",
    "set_model": "acp_set_model",
    "set_mode": "acp_set_mode",
    "set_session_autonomous": "acp_set_session_autonomous",
    "send_prompt": "acp_send_prompt",
    "cancel": "acp_cancel",
    "list_agents": "acp_list_agents",
    "install_agent": "acp_install_agent",
    "uninstall_agent": "acp_uninstall_agent",
    "get_capabilities": "acp_get_capabilities"
  },
  "session_history": {
    "get_session_history": "get_session_history",
    "get_session_messages": "get_session_messages",
    "get_full_session": "get_full_session",
    "get_converted_session": "get_converted_session",
    "get_cache_stats": "get_cache_stats",
    "invalidate_history_cache": "invalidate_history_cache",
    "reset_cache_stats": "reset_cache_stats"
  },
  "storage": {
    "save_conversation_metadata": "save_conversation_metadata",
    "get_conversation_metadata": "get_conversation_metadata",
    "get_all_conversation_metadata": "get_all_conversation_metadata",
    "delete_conversation_metadata": "delete_conversation_metadata",
    "update_conversation_metadata": "update_conversation_metadata",
    "delete_conversation": "delete_conversation",
    "open_in_finder": "open_in_finder",
    "open_streaming_log": "open_streaming_log",
    "get_projects": "get_projects",
    "get_recent_projects": "get_recent_projects",
    "get_project_count": "get_project_count",
    "get_missing_project_paths": "get_missing_project_paths",
    "import_project": "import_project",
    "add_project": "add_project",
    "update_project_color": "update_project_color",
    "update_project_icon": "update_project_icon",
    "update_project_order": "update_project_order",
    "remove_project": "remove_project",
    "browse_project": "browse_project",
    "get_all_conversations": "get_all_conversations",
    "upsert_conversation": "upsert_conversation",
    "get_user_setting": "get_user_setting",
    "save_user_setting": "save_user_setting",
    "get_panel_layout": "get_panel_layout",
    "save_panel_layout": "save_panel_layout",
    "clear_panel_layout": "clear_panel_layout",
    "get_thread_list_settings": "get_thread_list_settings",
    "save_thread_list_settings": "save_thread_list_settings",
    "get_api_key": "get_api_key",
    "save_api_key": "save_api_key",
    "delete_api_key": "delete_api_key",
    "get_user_keybindings": "get_user_keybindings",
    "save_user_keybinding": "save_user_keybinding",
    "delete_user_keybinding": "delete_user_keybinding",
    "reset_keybindings_to_defaults": "reset_keybindings_to_defaults"
  },
  "cursor_history": {
    "get_cursor_history": "get_cursor_history",
    "get_cursor_session": "get_cursor_session"
  },
  "github": {
    "get_github_repo_context": "get_github_repo_context",
    "list_pull_requests": "list_pull_requests",
    "fetch_commit_diff": "fetch_commit_diff",
    "fetch_pr_diff": "fetch_pr_diff",
    "git_working_file_diff": "git_working_file_diff"
  },
  "voice": {
    "list_models": "voice_list_models",
    "list_languages": "voice_list_languages",
    "get_model_status": "voice_get_model_status",
    "download_model": "voice_download_model",
    "delete_model": "voice_delete_model",
    "start_recording": "voice_start_recording",
    "stop_recording": "voice_stop_recording",
    "cancel_recording": "voice_cancel_recording",
    "load_model": "voice_load_model"
  }
} as const;
