// This file was generated by specta. Do not edit this file manually.

// JsonValue represents any valid JSON value
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

/**
 * Token counts for usage telemetry (generic, adapter-agnostic).
 */
export type UsageTelemetryTokens = { total?: number | null; input?: number | null; output?: number | null; cacheRead?: number | null; cacheWrite?: number | null; reasoning?: number | null }

/**
 * Payload for usage telemetry session update (generic, not provider-specific).
 */
export type UsageTelemetryData = { sessionId: string; eventId?: string | null; 
/**
 * Scope of the telemetry (e.g. "step", later "turn").
 */
scope?: string; costUsd?: number | null; tokens?: UsageTelemetryTokens; sourceModelId?: string | null; timestampMs?: number | null; 
/**
 * Context window size reported by the agent (e.g. from usage_update `size` field).
 */
contextWindowSize?: number | null }

export type AvailableModel = { modelId: string; name: string; description?: string | null }

export type AvailableMode = { id: string; name: string; description?: string | null }

/**
 * Pre-computed model info for display. Frontend uses this directly.
 */
export type DisplayableModel = { modelId: string; displayName: string; description?: string | null }

/**
 * Generic group of models. Label can be provider, base model name, or empty.
 */
export type DisplayModelGroup = { label: string; models: DisplayableModel[] }

export type ModelDisplayFamily = "claudeLike" | "codexReasoningEffort" | "providerGrouped"

export type UsageMetricsPresentation = "contextWindowOnly" | "spendAndContext"

export type ModelPresentationMetadata = { displayFamily: ModelDisplayFamily; usageMetrics: UsageMetricsPresentation }

/**
 * Display-ready model structure. Single representation—flat = one group.
 */
export type ModelsForDisplay = { groups: DisplayModelGroup[]; presentation?: ModelPresentationMetadata }

export type SessionModelState = { availableModels?: AvailableModel[]; currentModelId?: string; modelsDisplay?: ModelsForDisplay }

export type SessionModes = { currentModeId?: string; availableModes?: AvailableMode[] }

/**
 * Session update types from ACP protocol.
 * 
 * These are notifications sent by the agent during a prompt response.
 * They represent streaming updates to the session state.
 * 
 * Uses internally tagged representation with `type` field for clean TypeScript discrimination.
 * Example: `{ "type": "toolCall", "tool_call": {...}, "session_id": "..." }`
 */
export type SessionUpdate = { type: "userMessageChunk"; chunk: ContentChunk; session_id?: string | null } | { type: "agentMessageChunk"; chunk: ContentChunk; part_id?: string | null; message_id?: string | null; session_id?: string | null } | { type: "agentThoughtChunk"; chunk: ContentChunk; part_id?: string | null; message_id?: string | null; session_id?: string | null } | { type: "toolCall"; tool_call: ToolCallData; session_id?: string | null } | { type: "toolCallUpdate"; update: ToolCallUpdateData; session_id?: string | null } | { type: "plan"; plan: PlanData; session_id?: string | null } | { type: "availableCommandsUpdate"; update: AvailableCommandsData; session_id?: string | null } | { type: "currentModeUpdate"; update: CurrentModeData; session_id?: string | null } | { type: "configOptionUpdate"; update: ConfigOptionUpdateData; session_id?: string | null } | { type: "permissionRequest"; permission: PermissionData; session_id?: string | null } | { type: "questionRequest"; question: QuestionData; session_id?: string | null } | 
/**
 * Indicates that the current turn/prompt has completed.
 * This is emitted when the JSON-RPC response for a prompt request is received.
 */
{ type: "turnComplete"; session_id?: string | null } | 
/**
 * Indicates that the current turn/prompt failed with an error.
 * This is emitted when the JSON-RPC response contains an error.
 */
{ type: "turnError"; error: TurnErrorData; session_id?: string | null } | 
/**
 * Usage/cost and token telemetry from the agent (adapter-agnostic).
 * Emitted by adapters (e.g. OpenCode step-finish) for spend and context UI.
 */
{ type: "usageTelemetryUpdate"; data: UsageTelemetryData } | 
/**
 * Emitted by the async resume task when session connection completes successfully.
 * Carries the session capabilities so the frontend can populate hot state.
 */
{ type: "connectionComplete"; session_id: string; attempt_id: number; models: SessionModelState; modes: SessionModes; available_commands?: AvailableCommand[]; config_options?: ConfigOptionData[]; autonomous_enabled: boolean } | 
/**
 * Emitted by the async resume task when session connection fails.
 */
{ type: "connectionFailed"; session_id: string; attempt_id: number; error: string }

export type ChunkAggregationHint = "boundaryCarryover"

/**
 * ContentChunk represents a chunk of content being streamed.
 * 
 * This handles both direct format `{ content: ContentBlock }`
 * and nested format `{ chunk: { content: ContentBlock } }`.
 */
export type ContentChunk = { content: ContentBlock; aggregationHint?: ChunkAggregationHint | null }

/**
 * Tool call data.
 */
export type ToolCallData = { id: string; name: string; arguments: ToolArguments; rawInput?: JsonValue | null; status: ToolCallStatus; result?: JsonValue | null; kind?: ToolKind | null; title?: string | null; locations?: ToolCallLocation[] | null; skillMeta?: SkillMeta | null; 
/**
 * Normalized questions extracted from question tool calls.
 * This provides a unified format for questions across all agents.
 */
normalizedQuestions?: QuestionItem[] | null; 
/**
 * Normalized todos extracted from TodoWrite tool calls.
 * This provides a unified format for todos across all agents.
 */
normalizedTodos?: TodoItem[] | null; 
/**
 * Parent task ID for nested tool calls.
 */
parentToolUseId?: string | null; 
/**
 * Child tool calls belonging to this task.
 */
taskChildren?: ToolCallData[] | null; 
/**
 * Answered question data (questions + user's answers).
 * Present when this is a question tool call that has been answered.
 */
questionAnswer?: QuestionAnswer | null; 
/**
 * Whether this tool call is awaiting plan approval from the user.
 * Set on `cursor/create_plan` tool calls; the user must approve or reject before the agent continues.
 */
awaitingPlanApproval: boolean; 
/**
 * JSON-RPC request ID to use when responding to plan approval.
 * Present when `awaiting_plan_approval` is true.
 */
planApprovalRequestId?: number | null }

/**
 * A single canonical file delta within an Edit tool call.
 * 
 * A single `Edit` tool call may touch multiple files (e.g. OpenCode patch text
 * or Codex changes maps). Each entry must declare its semantic edit variant
 * explicitly instead of relying on a bag of optional transport-era fields.
 */
export type EditDelta = { type: "replaceText"; file_path?: string | null; move_from?: string | null; old_text?: string | null; new_text?: string | null } | { type: "writeFile"; file_path?: string | null; move_from?: string | null; previous_content?: string | null; content?: string | null } | { type: "deleteFile"; file_path?: string | null; old_text?: string | null }

/**
 * Tool arguments discriminated by tool kind.
 * Each variant contains exactly the fields needed for that tool type.
 */
export type ToolArguments = { kind: "read"; file_path?: string | null } | 
/**
 * Edit tool arguments.
 * 
 * `edits` is always a non-empty Vec. Single-file edits have exactly one entry;
 * multi-file edits (OpenCode `patch`, Codex multi-entry `changes` map) have N entries.
 */
{ kind: "edit"; edits: EditDelta[] } | { kind: "execute"; command?: string | null } | { kind: "search"; query?: string | null; file_path?: string | null } | { kind: "glob"; pattern?: string | null; path?: string | null } | { kind: "fetch"; url?: string | null } | { kind: "webSearch"; query?: string | null } | { kind: "think"; description?: string | null; prompt?: string | null; subagent_type?: string | null; skill?: string | null; skill_args?: string | null; raw?: JsonValue | null } | { kind: "taskOutput"; task_id?: string | null; timeout?: number | null } | { kind: "move"; from?: string | null; to?: string | null } | { kind: "delete"; file_path?: string | null; file_paths?: string[] | null } | { kind: "planMode"; mode?: string | null } | { kind: "toolSearch"; query?: string | null; max_results?: number | null } | { kind: "browser"; raw: JsonValue } | { kind: "other"; raw: JsonValue }

/**
 * Tool call update data.
 */
export type ToolCallUpdateData = { toolCallId: string; status?: ToolCallStatus | null; result?: JsonValue | null; content?: ContentBlock[] | null; rawOutput?: JsonValue | null; title?: string | null; locations?: ToolCallLocation[] | null; 
/**
 * Streaming input delta - partial JSON string for progressive tool input display.
 * Extracted from _meta.claudeCode.streamingInputDelta.
 */
streamingInputDelta?: string | null; 
/**
 * Progressive normalized todos from streaming input.
 * Populated by the streaming accumulator for TodoWrite-like tools.
 */
normalizedTodos?: TodoItem[] | null; 
/**
 * Progressive normalized questions from streaming input.
 * Populated by the streaming accumulator for AskUserQuestion-like tools.
 */
normalizedQuestions?: QuestionItem[] | null; 
/**
 * Pre-parsed streaming arguments for progressive tool input display.
 * Produced by the streaming accumulator when partial JSON parse succeeds.
 */
streamingArguments?: ToolArguments | null; 
/**
 * Typed tool arguments from rawInput in tool_call_update.
 * Upstream v0.18+ sends rawInput in the update, not the initial tool_call.
 */
arguments?: ToolArguments | null; 
/**
 * Human-readable reason when status is `Failed`.
 * Distinguishes user-denied permissions ("Permission denied by user")
 * from actual runtime failures without changing the status enum.
 */
failureReason?: string | null }

/**
 * Plan data with steps and optional current step index.
 * Also supports streaming plan content from Edit tool writes.
 */
export type PlanData = { steps: PlanStep[]; currentStep?: number | null; 
/**
 * Whether this payload currently represents an active plan.
 */
hasPlan?: boolean; 
/**
 * Whether the plan content is still streaming (true) or complete (false).
 */
streaming?: boolean; 
/**
 * The raw markdown content of the plan file (partial during streaming).
 */
content?: string | null; 
/**
 * Normalized markdown content consumed by the frontend.
 */
contentMarkdown?: string | null; 
/**
 * The file path where the plan is being written.
 */
filePath?: string | null; 
/**
 * The plan title extracted from the first # heading.
 */
title?: string | null; 
/**
 * Source quality of the signal.
 */
source?: PlanSource | null; 
/**
 * Confidence of the signal.
 */
confidence?: PlanConfidence | null; 
/**
 * Agent identifier that produced this plan.
 */
agentId?: string | null; 
/**
 * Last update timestamp in milliseconds.
 */
updatedAt?: number | null }

/**
 * Available commands update data.
 */
export type AvailableCommandsData = { availableCommands: AvailableCommand[] }

/**
 * Current mode update data.
 */
export type CurrentModeData = { currentModeId: string }

/**
 * Configuration options update data.
 */
export type ConfigOptionUpdateData = { configOptions: ConfigOptionData[] }

/**
 * Configuration option data.
 */
export type ConfigOptionData = { id: string; name: string; category: string; type: string; description?: string | null; currentValue?: JsonValue | null; options?: ConfigOptionValue[] }

/**
 * Configuration option value.
 */
export type ConfigOptionValue = { name: string; value: JsonValue; description?: string | null }

/**
 * Explicit reply routing metadata for a canonical interaction.
 */
export type InteractionReplyHandlerKind = "json_rpc" | "http"

/**
 * Backend-owned reply handler metadata for interaction replies.
 */
export type InteractionReplyHandler = { kind: InteractionReplyHandlerKind; requestId: string }

/**
 * Permission request data.
 */
export type PermissionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; permission: string; patterns: string[]; metadata: JsonValue; always: string[]; autoAccepted: boolean; tool?: ToolReference | null }

/**
 * Question request data.
 */
export type QuestionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; questions: QuestionItem[]; tool?: ToolReference | null }

/**
 * Turn error payload for compatibility during rollout.
 */
export type TurnErrorData = string | TurnErrorInfo

/**
 * Structured turn error payload.
 */
export type TurnErrorInfo = { message: string; kind: TurnErrorKind; code?: number | null; source?: TurnErrorSource | null }

/**
 * Turn error severity.
 */
export type TurnErrorKind = "recoverable" | "fatal"

/**
 * Turn error source.
 */
export type TurnErrorSource = "json_rpc" | "transport" | "process" | "unknown"

/**
 * Embedded resource data
 */
export type EmbeddedResource = { 
/**
 * URI of the resource
 */
uri: string; 
/**
 * Optional text content
 */
text?: string | null; 
/**
 * Optional base64-encoded blob content
 */
blob?: string | null; 
/**
 * Optional MIME type
 */
mimeType?: string | null }

/**
 * A single step in a plan.
 */
export type PlanStep = { description: string; status: PlanStepStatus }

/**
 * Plan step status.
 */
export type PlanStepStatus = "pending" | "in_progress" | "completed" | "failed"

/**
 * Plan signal source.
 */
export type PlanSource = "deterministic" | "heuristic"

/**
 * Confidence level for a plan signal.
 */
export type PlanConfidence = "high" | "medium"

/**
 * Tool kind for routing to appropriate UI components.
 */
export type ToolKind = "read" | "edit" | "execute" | "search" | "glob" | "fetch" | "web_search" | "think" | "todo" | "question" | "task" | "task_output" | "skill" | "move" | "delete" | "enter_plan_mode" | "exit_plan_mode" | "create_plan" | "tool_search" | "browser" | "other"

/**
 * The strongest signal that determined the canonical semantic kind for a tool event.
 */
export type ToolSemanticSource = "tool_name" | "provider_declared_kind" | "payload_hint" | "serialized_arguments" | "location_hint" | "title_hint" | "parsed_arguments" | "web_search_promotion" | "browser_override" | "unknown"

/**
 * Tool call status.
 */
export type ToolCallStatus = "pending" | "in_progress" | "completed" | "failed"

/**
 * Tool call location.
 */
export type ToolCallLocation = { path: string }

/**
 * Safe structured fallback when canonicalization cannot fully recover semantics.
 */
export type DegradedToolState = { reason: string; rawInputFragment?: JsonValue | null; rawResultFragment?: JsonValue | null; rawContentFragment?: JsonValue | null }

/**
 * Canonical operation-event envelope derived from tool transport.
 */
export type CanonicalOperationEvent = { transportId: string; provider: string; providerToolName?: string | null; providerDeclaredKind?: ToolKind | null; semanticKind: ToolKind; semanticSource: ToolSemanticSource; payload: ToolArguments; degraded?: DegradedToolState | null }

/**
 * Available command with metadata.
 */
export type AvailableCommand = { name: string; description: string; input?: CommandInput | null }

/**
 * Command input hint.
 */
export type CommandInput = { 
/**
 * The hint can be a string or array in the protocol; we normalize to string.
 */
hint: string }

/**
 * Tool reference for permission/question requests.
 */
export type ToolReference = { messageId: string; callId: string }

/**
 * Question option.
 */
export type QuestionOption = { label: string; description: string }

/**
 * Question item.
 */
export type QuestionItem = { question: string; header: string; options: QuestionOption[]; multiSelect: boolean }

/**
 * Todo item status.
 */
export type TodoStatus = "pending" | "in_progress" | "completed" | "cancelled"

/**
 * Todo item.
 */
export type TodoItem = { content: string; activeForm: string; status: TodoStatus; startedAt?: number | null; completedAt?: number | null; duration?: number | null }

/**
 * Statistics about the session
 */
export type SessionStats = { total_messages: number; user_messages: number; assistant_messages: number; tool_uses: number; tool_results: number; thinking_blocks: number; total_input_tokens: number; total_output_tokens: number }

/**
 * Token usage statistics from API response
 */
export type TokenUsage = { input_tokens?: number; output_tokens?: number; cache_read_input_tokens?: number; cache_creation_input_tokens?: number }

/**
 * Content block types per ACP protocol specification.
 * 
 * @see https://agentclientprotocol.com/protocol/schema#contentblock
 */
export type ContentBlock = 
/**
 * Text content block
 */
{ type: "text"; text: string } | 
/**
 * Image content block
 */
{ type: "image"; data: string; mimeType: string; uri?: string | null } | 
/**
 * Audio content block
 */
{ type: "audio"; data: string; mimeType: string } | 
/**
 * Embedded resource content block
 */
{ type: "resource"; resource: EmbeddedResource } | 
/**
 * Resource link content block
 */
{ type: "resource_link"; uri: string; name: string; title?: string | null; description?: string | null; mimeType?: string | null; size?: number | null }

/**
 * A message with ordering and full content
 */
export type OrderedMessage = { uuid: string; parent_uuid: string | null; role: string; timestamp: string; content_blocks: ContentBlock[]; model?: string | null; usage?: TokenUsage | null; request_id?: string | null; is_meta: boolean; 
/**
 * ID of the tool use this meta message is associated with (for skill content)
 */
source_tool_use_id?: string | null; 
/**
 * Tool use result data (for user messages that are tool results)
 * Contains questions and answers for AskUserQuestion tool
 */
tool_use_result?: JsonValue | null; 
/**
 * UUID of the assistant message containing the tool use that this result is for
 */
source_tool_assistant_uuid?: string | null }

/**
 * Full session data with ordered messages and metadata
 */
export type FullSession = { session_id: string; project_path: string; title: string; created_at: string; messages: OrderedMessage[]; stats: SessionStats }

/**
 * A content block in a user or assistant message.
 * Simplified version for storage/display.
 */
export type StoredContentBlock = { type: string; text?: string | null }

/**
 * A chunk of assistant message content (text or thought).
 */
export type StoredAssistantChunk = { type: string; block: StoredContentBlock }

/**
 * User message in a thread (simplified for storage).
 */
export type StoredUserMessage = { id?: string | null; content: StoredContentBlock; chunks: StoredContentBlock[]; sentAt?: string | null }

/**
 * Assistant message in a thread (simplified for storage).
 */
export type StoredAssistantMessage = { chunks: StoredAssistantChunk[]; model?: string | null; 
/**
 * User-friendly display name for the model (e.g., "Opus 4.5" instead of "claude-opus-4-5-20251101")
 */
displayModel?: string | null; receivedAt?: string | null }

/**
 * Skill metadata for skill tool calls.
 */
export type SkillMeta = { description?: string | null; filePath?: string | null }

/**
 * Answered question data from toolUseResult field in JSONL.
 * Stores both the questions and the user's answers.
 */
export type QuestionAnswer = { 
/**
 * The questions that were asked
 */
questions: QuestionItem[]; 
/**
 * Map of question text to answer(s) - value is string for single-select, array for multi-select
 */
answers: Partial<{ [key in string]: JsonValue }> }

/**
 * A single entry in the thread.
 * Discriminated union tagged by "type".
 */
export type StoredEntry = { type: "user"; id: string; message: StoredUserMessage; timestamp?: string | null } | { type: "assistant"; id: string; message: StoredAssistantMessage; timestamp?: string | null } | { type: "tool_call"; id: string; message: ToolCallData; timestamp?: string | null }

/**
 * Result of converting a full session to stored entries.
 * Returned by get_converted_session command.
 */
export type ConvertedSession = { entries: StoredEntry[]; stats: SessionStats; title: string; createdAt: string; currentModeId?: string | null }

/**
 * Response for session plan request.
 * Returned by get_session_plan, get_plan_by_slug, list_plans commands.
 */
export type SessionPlanResponse = { 
/**
 * Plan slug (filename without .md extension).
 */
slug: string; 
/**
 * Full markdown content of the plan.
 */
content: string; 
/**
 * Plan title (extracted from first # heading).
 */
title: string; 
/**
 * Plan summary (first paragraph after title, if any).
 */
summary: string | null; 
/**
 * Full file path to the plan file (for revealing in file manager).
 */
filePath: string | null }

/**
 * User setting keys for the app_settings table.
 * These are the allowed keys for save_user_setting/get_user_setting commands.
 */
export type UserSettingKey = 
/**
 * User's preferred theme (light, dark, system)
 */
"user_theme" | 
/**
 * User's preferred locale/language
 */
"user_locale" | 
/**
 * Workspace panel layout state (JSON)
 */
"workspace_state" | 
/**
 * Custom keybindings (JSON map of command -> key)
 */
"custom_keybindings" | 
/**
 * Streaming text animation style (none, fade, glow, typewriter)
 */
"streaming_animation" | 
/**
 * Webview zoom level (stored as float string, e.g., "1.0", "1.2")
 */
"zoom_level" | 
/**
 * Default models per agent per mode (JSON map)
 */
"agent_default_models" | 
/**
 * Favorite models per agent (JSON map)
 */
"agent_favorite_models" | 
/**
 * Cached available models per agent (JSON map)
 */
"agent_available_models_cache" | 
/**
 * Cached available models display groups per agent (JSON map)
 */
"agent_available_models_display_cache" | 
/**
 * Cached provider metadata per agent (JSON map)
 */
"agent_provider_metadata_cache" | 
/**
 * Cached available modes per agent (JSON map)
 */
"agent_available_modes_cache" | 
/**
 * Per-session model memory (JSON map)
 */
"session_model_per_mode" | 
/**
 * Global PR generation preferences (JSON object)
 */
"pr_generation_preferences" | 
/**
 * Command palette recent items (JSON array)
 */
"command_palette_recent_items" | 
/**
 * OpenCode favorite models (JSON array)
 */
"favorite_models" | 
/**
 * OpenCode recent models (JSON array)
 */
"recent_models" | 
/**
 * Whether user has seen the splash screen (boolean string "true"/"false")
 */
"has_seen_splash" | 
/**
 * Last app version the user has seen the changelog for
 */
"last_seen_version" | 
/**
 * Whether user has completed first-run onboarding
 */
"has_completed_onboarding" | 
/**
 * Selected agent IDs for UI visibility/filtering (JSON array)
 */
"selected_agent_ids" | 
/**
 * Persisted custom agent configurations (JSON array)
 */
"custom_agent_configs" | 
/**
 * Persisted per-agent environment overrides (JSON object)
 */
"agent_env_overrides" | 
/**
 * Whether opening review should use full-screen overlay (boolean string "true"/"false")
 */
"review_prefer_fullscreen" | 
/**
 * Use worktrees by default for new sessions (boolean)
 */
"worktree_global_default_enabled" | 
/**
 * Workspace trust decisions for setup commands (JSON map: path key -> { trusted, commands })
 */
"worktree_trust" | 
/**
 * Whether thinking blocks in chat are collapsed by default (boolean)
 */
"chat_thinking_block_collapsed_by_default" | 
/**
 * Whether plans render inline in chat vs sidebar panel (boolean)
 */
"plan_inline_mode" | 
/**
 * Per-category notification preferences (JSON object)
 */
"notification-preferences" | 
/**
 * Selected voice model ID (e.g. "small.en")
 */
"voice_model" | 
/**
 * Preferred voice transcription language code (e.g. "en" or "auto")
 */
"voice_language" | 
/**
 * Whether voice dictation is enabled (boolean)
 */
"voice_enabled" | 
/**
 * Agent ID used for AI-generated commit messages and PR descriptions
 */
"git_text_generation_agent" | 
/**
 * Preferred merge strategy for PRs (e.g., "squash", "merge", "rebase")
 */
"git_merge_strategy_preference" | 
/**
 * Set of dismissed tooltip keys (JSON array of string keys)
 */
"dismissed_tooltips" | 
/**
 * Whether the attention queue panel is shown in the sidebar (boolean, default false)
 */
"attention_queue_enabled"

/**
 * Information about a single indexed file.
 */
export type IndexedFile = { 
/**
 * Relative path from project root.
 */
path: string; 
/**
 * File extension without dot, empty for no extension.
 */
extension: string; 
/**
 * Number of lines in the file.
 */
lineCount: number; 
/**
 * Git status info if file is modified/added/deleted, or None.
 */
gitStatus: FileGitStatus | null }

/**
 * Git status for a single file.
 */
export type FileGitStatus = { 
/**
 * Relative path from project root.
 */
path: string; 
/**
 * Status code: M=Modified, A=Added, D=Deleted, ?=Untracked, R=Renamed.
 */
status: string; 
/**
 * Lines added (for modified/added files).
 */
insertions: number; 
/**
 * Lines deleted (for modified/deleted files).
 */
deletions: number }

/**
 * Complete project index result.
 */
export type ProjectIndex = { 
/**
 * Project root path.
 */
projectPath: string; 
/**
 * All indexed files.
 */
files: IndexedFile[]; 
/**
 * Git-tracked modified files with status.
 */
gitStatus: FileGitStatus[]; 
/**
 * Total file count.
 */
totalFiles: number; 
/**
 * Total line count across all files.
 */
totalLines: number }

/**
 * What kind of preview the frontend should render for a result row.
 */
export type PreviewKind = 
/**
 * Changed text file — Pierre diff is safe to render.
 */
"diff" | 
/**
 * Unchanged text file — Pierre read-view is safe to render.
 */
"text" | 
/**
 * Detected as binary content.
 */
"binary" | 
/**
 * File exceeds safe preview size.
 */
"large" | 
/**
 * File has been deleted from the working tree.
 */
"deleted" | 
/**
 * Unsupported content type for preview.
 */
"unsupported"

/**
 * A single row in the file explorer results list.
 */
export type FileExplorerRow = { 
/**
 * Absolute path to the owning project root.
 */
projectPath: string; 
/**
 * Relative path from project root.
 */
path: string; 
/**
 * Basename of the file.
 */
fileName: string; 
/**
 * File extension without dot, empty for no extension.
 */
extension: string; 
/**
 * Path split into segments for breadcrumb display.
 */
pathSegments: string[]; 
/**
 * Git status if the file has been modified/added/deleted/etc.
 */
gitStatus: FileGitStatus | null; 
/**
 * Whether the file is tracked by git.
 */
isTracked: boolean; 
/**
 * Whether the file appears to be binary content.
 */
isBinary: boolean; 
/**
 * File last-modified time in milliseconds since Unix epoch, if available.
 */
lastModifiedMs: number | null; 
/**
 * File size in bytes, if available.
 */
sizeBytes: number | null; 
/**
 * Classification hint for the preview pane.
 */
previewKind: PreviewKind }

/**
 * Response from the explorer search command.
 */
export type FileExplorerSearchResponse = { 
/**
 * Project path echoed back.
 */
projectPath: string; 
/**
 * Query echoed back.
 */
query: string; 
/**
 * Total number of matching rows before limiting/offsetting.
 */
total: number; 
/**
 * Ranked result rows for this page.
 */
rows: FileExplorerRow[] }

/**
 * Preview payload returned for a selected explorer row.
 */
export type FileExplorerPreviewResponse = 
/**
 * Changed text file with diff content.
 */
{ kind: "diff"; file_path: string; file_name: string; old_content: string | null; new_content: string; git_status: FileGitStatus } | 
/**
 * Unchanged text file with full content.
 */
{ kind: "text"; file_path: string; file_name: string; content: string; language_hint: string | null } | 
/**
 * Fallback for binary, too-large, deleted, or unsupported files.
 */
{ kind: "fallback"; file_path: string; file_name: string; reason: string; size_bytes: number | null; git_status: FileGitStatus | null; preview_kind: PreviewKind }

