export enum SoundEffect {
	AppStartFinish = "app-start-finish.wav",
	AppStart = "app-start.wav",
	SoundDown = "sound-down.mp3",
	SoundUp = "sound-up-2.mp3",
	Notification = "Notification.wav",
	DictationStart = "dictation-start.wav",
	DictationStop = "dictation-stop.wav",
	AnthonyHopkins = "AnthonyHopkins.wav",
	BradPitt = "BradPitt.wav",
	CateBlanchett = "CateBlanchett.wav",
	DanielDayLewis = "DanielDayLewis.wav",
	DenzelWashington = "DenzelWashington.wav",
	EmmaStone = "EmmaStone.mp3",
	GeorgeClooney = "GeorgeClooney.mp3",
	JuliaRoberts = "JuliaRoberts.mp3",
	LeonardoDiCaprio = "LeonardoDiCaprio.mp3",
	MerylStreep = "MerylStreep.mp3",
	MorganFreeman = "MorganFreeman.mp3",
	NicoleKidman = "NicoleKidman.mp3",
	ScarlettJohansson = "ScarlettJohansson.wav",
	TomHanks = "TomHanks.wav",
}
